"""User last_seen fix

Revision ID: 751c1e6d4a35
Revises: 18d513bcacb4
Create Date: 2019-06-12 21:15:55.435689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751c1e6d4a35'
down_revision = '18d513bcacb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
